project:
  type: book

book:
  title: "Machine Learning for Predictive Analytics in Business"
  author: "Bowei Chen"
  date: today
  chapters:
    - index.qmd
    - about.qmd
    - introduction.qmd
  appendices:
    - bibliography.qmd

bibliography: bibliography.bib

format:
  html:
    toc: true
    number-sections: true
    highlight-style: github
    cite-method: citeproc
    theme: cosmo
    
editor: visual


